# Generated by Django 3.2.9 on 2021-11-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbook',
            name='is_delete',
        ),
    ]
