# Generated by Django 3.2.9 on 2021-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0002_remove_accountbook_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
